services:
  app:
    build:
      context: .
      args:
        - APP_PORT=${APP_PORT} # Pass APP_PORT as a build argument
    ports:
      - "${APP_PORT}:${APP_PORT}" # Use the PORT variable from .env
    volumes:
      - .:/app
      - /app/node_modules
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - NODE_ENV=${NODE_ENV}
      - APP_PORT=${APP_PORT} # Pass the PORT variable to the container
      - DB_TYPE=${DB_TYPE}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
      # Mail configuration
      - MAIL_HOST=${MAIL_HOST}
      - MAIL_PORT=${MAIL_PORT}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      # JWT configuration
      - JWT_SECRET=${JWT_SECRET}
    command: npm run start:dev